"""
TwiML endpoint — Twilio fetches this URL when the call connects.
Returns TwiML XML that reads the call_script using Polly voice.
"""
from fastapi import APIRouter
from fastapi.responses import Response

twiml_router = APIRouter()


@twiml_router.get(
    "/twiml/brief/{disruption_id}",
    response_class=Response,
    include_in_schema=True,
    tags=["TwiML"],
)
async def get_twiml(disruption_id: str):
    """
    Serve TwiML for an outbound Twilio call.
    Twilio calls this URL when the recipient answers.
    """
    from engine.calling_agent import get_call_script

    script = get_call_script(disruption_id)

    # Escape XML special characters
    safe_script = (
        script
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )

    twiml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Say voice="Polly.Matthew" language="en-US">
    {safe_script}
  </Say>
  <Pause length="1"/>
  <Say voice="Polly.Matthew" language="en-US">
    This message was generated by FreightPulse AI. Please log in to review and take action.
  </Say>
</Response>"""

    return Response(content=twiml, media_type="application/xml")
