export const MOCK_DATA = {
  shipments: [
    {
      id: "SHP-001",
      origin: "Mundra",
      destination: "Rotterdam",
      vessel: "MSC MAYA",
      eta: "2026-06-22",
      cargoValue: 1850000,
      forwarderName: "Mehta Freight Services",
      forwarderPhone: "+91-98765-43210",
      alertSeverity: "critical",
      riskScore: 87
    },
    {
      id: "SHP-002",
      origin: "JNPT",
      destination: "Hamburg",
      vessel: "EVER GIVEN II",
      eta: "2026-06-28",
      cargoValue: 720000,
      forwarderName: "TransOcean Logistics",
      forwarderPhone: "+91-98123-45678",
      alertSeverity: "watch",
      riskScore: 44
    },
    {
      id: "SHP-003",
      origin: "Chennai",
      destination: "Felixstowe",
      vessel: "COSCO SHANGHAI",
      eta: "2026-07-04",
      cargoValue: 2300000,
      forwarderName: "BlueStar Forwarders",
      forwarderPhone: "+91-97890-12345",
      alertSeverity: null,
      riskScore: 12
    }
  ],
  signals: [
    {
      id: "SIG-001",
      source: "GDELT",
      title: "Port workers' union announces 72-hr strike at Rotterdam Europoort",
      timestamp: "2026-06-10T04:34:00Z",
      simulated: false,
      affectedPort: "Rotterdam"
    },
    {
      id: "SIG-002",
      source: "Weather",
      title: "Severe storm system tracking toward North Sea — winds 60+ knots forecast",
      timestamp: "2026-06-10T05:11:00Z",
      simulated: false,
      affectedPort: "Rotterdam"
    },
    {
      id: "SIG-003",
      source: "Congestion",
      title: "Hamburg Terminal 4 berth wait time: 38 hrs (up from 6 hrs baseline)",
      timestamp: "2026-06-10T05:48:00Z",
      simulated: true,
      affectedPort: "Hamburg"
    },
    {
      id: "SIG-004",
      source: "AIS",
      title: "MSC MAYA — AIS transponder dark for 4h 12m near Strait of Gibraltar",
      timestamp: "2026-06-10T06:02:00Z",
      simulated: true,
      affectedPort: null
    }
  ],
  alerts: [
    {
      id: "ALT-001",
      severity: "critical",
      disruptionTitle: "Rotterdam Port Strike — 72-hour work stoppage confirmed",
      description: "The Rotterdam Europoort dockers' union has confirmed a 72-hour strike beginning June 14. All container terminal operations will cease. Vessels in queue will be diverted or held at anchorage.",
      affectedShipmentIds: ["SHP-001"],
      affectedCount: 1,
      estimatedDelayDays: 5,
      estimatedCostImpact: 480000,
      actWithinHours: 18,
      timestamp: "2026-06-10T06:04:00Z"
    }
  ],
  timeline: [
    { time: "06:04 AM", icon: "⚡", label: "Precursor signal detected", detail: "GDELT news item flagged: Rotterdam labour dispute escalation", type: "signal" },
    { time: "06:04 AM", icon: "🚨", label: "Disruption confirmed", detail: "Cross-referenced with 2 additional sources — confidence: HIGH", type: "confirm" },
    { time: "06:04 AM", icon: "📦", label: "1 shipment matched", detail: "SHP-001 — Rotterdam ETA June 22 — inside strike window", type: "match" },
    { time: "06:04 AM", icon: "📋", label: "Forwarder Brief generated", detail: "Sent to Mehta Freight Services via WhatsApp", type: "brief" }
  ],
  briefText: `**DISRUPTION SUMMARY:**
Rotterdam Port Strike — 72-hour work stoppage confirmed beginning June 14, 2026. All container terminal operations at Europoort will cease. This is a confirmed, high-confidence disruption sourced from GDELT news intelligence and cross-referenced with port authority communications.

**AFFECTED SHIPMENTS:**
• SHP-001 | MSC MAYA | Mundra → Rotterdam | ETA: June 22
  Cargo Value: ₹18,50,000 | Status: CRITICAL
  This vessel will arrive during the strike window. Expect 4–6 day delay minimum.

**RECOMMENDED ACTIONS:**
1. Contact Rotterdam port agent immediately to explore diversion to Antwerp or Zeebrugge
2. Notify buyer of potential 5-day delay and negotiate revised delivery window
3. Check insurance coverage for strike-related delays under Force Majeure clause
4. Monitor situation — FreightPulse will push real-time updates as the strike progresses

**COST IMPACT ESTIMATE:**
Estimated additional cost: ₹4,80,000
  - Demurrage: ₹2,40,000 (est. 5 days × ₹48,000/day)
  - Rerouting surcharge: ₹1,60,000
  - Documentation & handling: ₹80,000

**URGENCY:**
Act within 18 hours to secure alternative berth allocation. Diversion options narrow significantly after June 12.

Generated by FreightPulse AI at ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`
};
